import { CreateTaskDto } from './../dto/create-task.dto';
import { Injectable } from '@nestjs/common';
import { v4 as uuid } from 'uuid';

import { Task, TaskStatus } from './task.module';

@Injectable()
export class TasksService {
   private tasks: Task[] = []

//    Function to return all tasks
    getAllTasks(): Task[]{
        return this.tasks
    }

    // Function to create a task. However, the id will be autogenerated and status will be open by default
    createNewTask(CreateTaskDto: CreateTaskDto): Task{
        // Destructure title and decription from the DTO
        const {title, description} = CreateTaskDto
        const task: Task = {
            id: uuid(),
            title,
            description,
            status: TaskStatus.OPEN
        }

        // Push it to the task array
        this.tasks.push(task)
        // Return the task to our controller
        return task
    }
}
