import { GetTaskFilterDto } from './../dto/get-task-filter';
import { UpdateTaskStatusDto } from './../dto/update-task-status.dto';
import { CreateTaskDto } from './../dto/create-task.dto';
import { Injectable } from '@nestjs/common';
import { v4 as uuid } from 'uuid';

import { Task, TaskStatus } from './task.module';

@Injectable()
export class TasksService {
   private tasks: Task[] = []

//    Function to return all tasks
    getAllTasks(): Task[]{
        return this.tasks
    }

    // Funtion to fetch a task by a given ID in the param
    getTakById(id: string): Task{
        // If a id was found then return that item
        return this.tasks.find(task => task.id === id)
    }

    // run funcion to get tasks when filter is provided
    getTaskWithFilters(filterDTO: GetTaskFilterDto): Task[]{
        // Extract status and search from filterDTO
        const {status, search} = filterDTO

        // Define a temporary array variable to holdd the result
        let task = this.getAllTasks()

        // If search is defined run statement
        if(search){
            task = task.filter(item=>item.title.toLowerCase().includes(search) || item.description.includes(search)?true:false)
        }

        // If status is defined run statement
        if(status){
            task = task.filter(item=>item.status === status)
        }

        // Return the final result
        return task
    }

    // Function to create a task. However, the id will be autogenerated and status will be open by default
    createNewTask(CreateTaskDto: CreateTaskDto): Task{
        // Destructure title and decription from the DTO
        const {title, description} = CreateTaskDto
        const task: Task = {
            id: uuid(),
            title,
            description,
            status: TaskStatus.OPEN
        }

        // Push it to the task array
        this.tasks.push(task)
        // Return the task to our controller
        return task
    }

    // Delete a task by Id\
    deleteTaskById(id: string): void{
        this.tasks = this.tasks.filter(task => task.id !== id)
    }

    updateTaskStatus(id, UpdateTaskStatusDto:UpdateTaskStatusDto): Task{
        const task = this.getTakById(id)
        const {status} = UpdateTaskStatusDto
        task.status=status
        return task
    }
}
